### ISSUE TITLE
Improve the exercise!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m1-evaluacion-intermedia-ayelenperezdemendiola#1]
Really cool job @ayelenperezdemendiola  !!!

Here you have some tips to improve the exercise:

## HTML
- [ ] Fix the language of the page
- [ ] Should the `.menu` element be a non-semantics `div` or a rich semantic `nav` (commonly used for our main navigation)
- [ ] Menu items should be inside an unordered list
- [ ] Menu items should be clickable

## CSS - structure
- [ ] Move the font CSS before your main CSS

## CSS - selectors
- [ ] Class selectors are free, let's use them instead tag selectors 
- [ ] Improve hierarchy adding more common styles to `body` tag as font-size, font-family, font-weight, color, background color

## CSS - other
- [ ] Avoid  `BR` tags, we can transform the text with CSS; this way we keep concepts separated, HTML for content, and CSS for styles
- [ ] Fix color of links and appearance.

## Good practices
- [ ] Try to improve your commit messages, better in English and using imperative
- [ ] Organize your files in folders, you have a guide to help you with that here --> https://books.adalab.es/materiales-front-end-g/modulo-1.-hola-mundo/1_1_intro_a_la_web#notas-finales-sobre-como-organizar-nuestro-proyecto

Let me know if you have any doubts ;)

Go for it!!

**Comment by ayelenperezdemendiola** [comment]
¡Hola Carlos! 

Realicé una nueva rama para mi evaluación que se llama "evaluation-remake".

Tengo una pequeña duda, en función de los que vimos al principio del curso no debería hacer divs de más si no los necesito; pero en función de lo que vimos hoy debería hacerlos justamente para separar la semántica de la decoración. 

¿Para este ejercicio sería necesario que agregue más divs o directamente, al ser "sencillo", puedo trabajar el css con las clases?

Muchas gracias :)

Ayelen
---

**Comment by oneeyedman** [comment]
Buen trabajo, @ayelenperezdemendiola. Mézclalo con master.

**Comment by ayelenperezdemendiola** [comment]
Hecho :) Nos vemos mañana, muchas gracias!
